version: '3'
services:
  back-end:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "5001:5001"
    volumes: 
     - ./dataloader/data:/dataloader/data:ro
  front-end:
    build:
        context: .
        dockerfile: Dockerfile-frontend
    ports:
      - "8081:8080"